# Generated by Django 5.0.6 on 2024-06-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_category_alter_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='steps_is_html',
            new_name='preparation_steps_is_html',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='preparation_unit',
            new_name='preparation_time_unit',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='serving_unit',
            new_name='servings_unit',
        ),
    ]
